# Generated by Django 5.1.7 on 2025-03-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerycore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_file',
        ),
    ]
