# Generated by Django 5.1.7 on 2025-03-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerycore', '0003_image_thumbnail_url_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favourite',
        ),
    ]
