# Generated by Django 5.1.7 on 2025-03-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerycore', '0004_rename_favorite_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_file',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
