# Generated by Django 5.1.7 on 2025-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerycore', '0007_alter_image_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
