# Generated by Django 5.1.7 on 2025-03-11 10:34

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerycore', '0008_alter_image_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='images/'),
        ),
    ]
