# Generated by Django 5.1.7 on 2025-03-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerycore', '0010_remove_image_thumbnail_file_image_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
